name: yolov4-gpu

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - cudnn
  - cudatoolkit==10.1.243
  - pip:
    - tensorflow-gpu==2.3
    - opencv-python==4.4.0.44
    - lxml
    - tqdm
    - absl-py
    - easydict
    - pillow
